CREATE TABLE [mhp].[MHP_Yearly_Universes](
	[mhp_uni_id] [bigint]  NOT NULL,
	[State_of_Issue] [char](2) NULL,
	[State_of_Residence] [char](2) NULL,
	[Enrollee_First_Name] [varchar](255) NULL,
	[Enrollee_Last_Name] [varchar](255) NULL,
	[Cardholder_ID] [varchar](25) NULL,
	[Funding_Arrangement] [varchar](50) NULL,
	[Authorization] [varchar](25) NULL,
	[Authorization_Type] [char](2) NULL,
	[Request_Date] [date] NULL,
	[Request_Time] [time](7) NULL,
	[Request_Decision] [char](3) NULL,
	[Decision_Date] [date] NULL,
	[Decision_Time] [time](7) NULL,
	[Decision_Reason] [varchar](255) NULL,
	[Extension_Taken] [bit] NULL,
	[Member_Notif_Extension_Date] [date] NULL,
	[Additional_Info_Date] [date] NULL,
	[Oral_Notification_Enrollee_Date] [date] NULL,
	[Oral_Notification_Enrollee_Time] [time](7) NULL,
	[Oral_Notification_Provider_Date] [date] NULL,
	[Oral_Notification_Provider_Time] [time](7) NULL,
	[Written_Notification_Enrollee_Date] [date] NULL,
	[Written_Notification_Enrollee_Time] [time](7) NULL,
	[Written_Notification_Provider_Date] [date] NULL,
	[Written_Notification_Provider_Time] [time](7) NULL,
	[Primary_Procedure_Code_Req] [varchar](50) NULL,
	[Procedure_Code_Description] [varchar](max) NULL,
	[Primary_Diagnosis_Code] [varchar](50) NULL,
	[Diagnosis_Code_Description] [varchar](max) NULL,
	[Place_of_Service] [smallint] NULL,
	[Member_Date_of_Birth] [date] NULL,
	[Urgent_Processed_Standard] [bit] NULL,
	[Request_Additional_Info_Date] [date] NULL,
	[FirstTier_Downstream_RelatedEntity] [varchar](55) NULL,
	[Par_NonPar_Site] [varchar](25) NULL,
	[Inpatient_Outpatient] [varchar](25) NULL,
	[Delegate_Number] [int] NULL,
	[ProgramType] [varchar](50) NULL,
	[Insurance_Carrier] [varchar](50) NULL,
	[Group_Number] [varchar](50) NULL,
	[classification] [varchar](10) NULL,
	[sheet_name] [varchar](35) NULL,
	[file_name] [varchar](255) NULL,
	[file_path] [varchar](255) NULL,
	[file_date] [date] NULL,
	[file_month] [int] NULL,
	[file_year] [int] NULL,
	[insert_date] [date] NULL,
	[ugap_process_date] [date] NULL,
	[Intake_Method] [varchar](25) NULL,
 CONSTRAINT [PK_MHP_Yearly_Universes] PRIMARY KEY CLUSTERED 
(
	[mhp_uni_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
