CREATE TABLE [dbo].[ChemotherapyPX]
(
	[Id] SMALLINT NOT NULL PRIMARY KEY IDENTITY, 
    [CODE] VARCHAR(7) NOT NULL, 
    [CODE_DESC] VARCHAR(100) NULL, 
    [GENERIC_NAME] VARCHAR(100) NULL, 
    [TRADE_NAME] VARCHAR(50) NULL, 
    [CKPT_INHIB_IND] BIT NULL, 
    [ANTI_EMETIC_IND] BIT NULL, 
    [CODE_TYPE] VARCHAR(10) NULL, 
    [CODE_EFF_DT] DATE NULL, 
    [CODE_END_DT] DATE NULL, 
    [NHNR_CANCER_THERAPY] BIT NULL, 
	[CODE_CATEGORY_ID] SMALLINT NULL, 
	[ASP_CATEGORY_ID] SMALLINT NULL, 
	[DRUG_ADM_MODE_ID] SMALLINT NULL, 
	[PA_DRUGS_ID] SMALLINT NULL, 
    [PA_EFF_DT] DATE NULL, 
    [PA_END_DT] DATE NULL, 
	[CEP_PAY_CD_ID] SMALLINT NULL, 
    [CEP_ENROLL_CD_ID] VARCHAR(12) NULL, 
    [CEP_ENROLL_EXCL_DESC] VARCHAR(12) NULL, 
    [NOVEL_STATUS_IND] BIT NULL, 
    [FIRST_NOVEL_MNTH] INT NULL, 
    [SOURCE] VARCHAR(255) NULL, 
    [UPDATE_DT] DATE NULL,
    [Is_Archived] BIT NULL


)
