CREATE VIEW [etg].[VW_ETG_Final_DataLoad]
	AS 

	select pc.Premium_Specialty,
	pc.ETG_Base_Class,
	ec.EC_Treatment_Indicator,
	pc.PC_Episode_Count,
	pc.PC_Total_Cost,
	pc.PC_Average_Cost,
	pc.PC_Coefficients_of_Variation,
	pc.PC_Normalized_Pricing_Episode_Count,
	pc.PC_Normalized_Pricing_Total_Cost,
	pc.PC_Spec_Episode_Count,
	pc.PC_Spec_Total_Cost,
	pc.PC_Spec_Average_Cost,
	pc.PC_Spec_CV,
	pc.PC_Spec_Percent_of_Episodes,
	pc.PC_Spec_Normalized_Pricing_Episode_Count,
	pc.PC_Spec_Normalized_Pricing_Total_Cost,
	pc.PC_Spec_Epsd_Volume,
	ec.EC_Episode_Count,
	ec.EC_Total_Cost,
	ec.EC_Average_Cost,
	ec.EC_Coefficients_of_Variation,
	ec.EC_Normalized_Pricing_Episode_Count,
	ec.EC_Normalized_Pricing_Total_Cost,
	ec.EC_Spec_Episode_Count,
	ec.EC_Spec_Total_Cost,
	ec.EC_Spec_Average_Cost,
	ec.EC_Spec_Coefficients_of_Variation,
	ec.EC_Spec_Percent_of_Episodes,
	ec.EC_Spec_Normalized_Pricing_Episode_Count,
	ec.EC_Spec_Normalized_Pricing_Total_Cost,
	ec.EC_CV3,
	ec.EC_Spec_Episode_Volume,
	ec.PD_Mapped,
	pc.PC_CV3,
	nrx.RX_NRX,
	nrx.Has_RX,
	nrx.Has_NRX,
	nrx.RX,
	nrx.NRX 
from etg.ETG_Dataload_PC_AGG pc 
	left join etg.ETG_Dataload_EC_AGG ec on pc.Premium_Specialty = ec.Premium_Specialty and pc.ETG_Base_Class = ec.ETG_Base_Class 
	left join etg.ETG_Dataload_NRX_AGG nrx on pc.ETG_Base_Class = nrx.ETG_Base_Class