CREATE PROCEDURE [chemopx].[sp_ChemotherapyPX_BulkCUD]
	@username varchar(10),
	@update_date DATETIME
AS
 --DELETE
    UPDATE [chemopx].[ChemotherapyPX] SET [Is_Archived] = 1 WHERE [Id] in 
  (SELECT [ChemoPX_Id] FROM [chemopx].[ChemotherapyPX_Tracking]   WHERE [UPDATE_USER] = @username AND UPDATE_DT = @update_date AND [UPDATE_ACTION] = 'DELETE')

UPDATE Track
SET 
Track.[GENERIC_NAME] = Chemo.[GENERIC_NAME],
Track.[TRADE_NAME] = Chemo.[TRADE_NAME],
Track.[CKPT_INHIB_IND] = Chemo.[CKPT_INHIB_IND],
Track.[ANTI_EMETIC_IND] = Chemo.[ANTI_EMETIC_IND],
Track.[CODE_EFF_DT] = Chemo.[CODE_EFF_DT],
Track.[NHNR_CANCER_THERAPY] = Chemo.[NHNR_CANCER_THERAPY],
Track.[CODE_CATEGORY_ID] = Chemo.[CODE_CATEGORY_ID],
Track.[ASP_CATEGORY_ID] = Chemo.[ASP_CATEGORY_ID],
Track.[DRUG_ADM_MODE_ID] = Chemo.[DRUG_ADM_MODE_ID],
Track.[PA_DRUGS_ID] = Chemo.[PA_DRUGS_ID],
Track.[PA_EFF_DT] = Chemo.[PA_EFF_DT],
Track.[PA_END_DT] = Chemo.[PA_END_DT],
Track.[CEP_PAY_CD_ID] = Chemo.[CEP_PAY_CD_ID],
Track.[CEP_ENROLL_CD_ID] = Chemo.[CEP_ENROLL_CD_ID],
Track.[CEP_ENROLL_EXCL_DESC] = Chemo.[CEP_ENROLL_EXCL_DESC],
Track.[NOVEL_STATUS_IND] = Chemo.[NOVEL_STATUS_IND],
Track.[FIRST_NOVEL_MNTH] = Chemo.[FIRST_NOVEL_MNTH],
Track.[SOURCE] = Chemo.[SOURCE],
Track.[GENERIC_NAME_PREVIOUS] = Chemo.[GENERIC_NAME],
Track.[TRADE_NAME_PREVIOUS] = Chemo.[TRADE_NAME],
Track.[CKPT_INHIB_IND_PREVIOUS] = Chemo.[CKPT_INHIB_IND],
Track.[ANTI_EMETIC_IND_PREVIOUS] = Chemo.[ANTI_EMETIC_IND],
Track.[CODE_EFF_DT_PREVIOUS] = Chemo.[CODE_EFF_DT],
Track.[NHNR_CANCER_THERAPY_PREVIOUS] = Chemo.[NHNR_CANCER_THERAPY],
Track.[CODE_CATEGORY_ID_PREVIOUS] = Chemo.[CODE_CATEGORY_ID],
Track.[ASP_CATEGORY_ID_PREVIOUS] = Chemo.[ASP_CATEGORY_ID],
Track.[DRUG_ADM_MODE_ID_PREVIOUS] = Chemo.[DRUG_ADM_MODE_ID],
Track.[PA_DRUGS_ID_PREVIOUS] = Chemo.[PA_DRUGS_ID],
Track.[PA_EFF_DT_PREVIOUS] = Chemo.[PA_EFF_DT],
Track.[PA_END_DT_PREVIOUS] = Chemo.[PA_END_DT],
Track.[CEP_PAY_CD_ID_PREVIOUS] = Chemo.[CEP_PAY_CD_ID],
Track.[CEP_ENROLL_CD_ID_PREVIOUS] = Chemo.[CEP_ENROLL_CD_ID],
Track.[CEP_ENROLL_EXCL_DESC_PREVIOUS] = Chemo.[CEP_ENROLL_EXCL_DESC],
Track.[NOVEL_STATUS_IND_PREVIOUS] = Chemo.[NOVEL_STATUS_IND],
Track.[FIRST_NOVEL_MNTH_PREVIOUS] = Chemo.[FIRST_NOVEL_MNTH],
Track.[SOURCE_PREVIOUS] = Chemo.[SOURCE]
FROM [chemopx].[ChemotherapyPX_Tracking] Track
INNER JOIN 
[chemopx].[ChemotherapyPX] Chemo
ON Chemo.[CODE] = Track.[CODE]
WHERE Track.[UPDATE_USER] = @username AND Track.UPDATE_DT =@update_date AND Track.[UPDATE_ACTION] = 'DELETE'





  --INSERT
INSERT INTO [chemopx].[ChemotherapyPX] ([CODE] ,[GENERIC_NAME] ,[TRADE_NAME] ,[CKPT_INHIB_IND] ,[ANTI_EMETIC_IND] ,[CODE_EFF_DT] ,[NHNR_CANCER_THERAPY] ,[CODE_CATEGORY_ID] ,[ASP_CATEGORY_ID] ,[DRUG_ADM_MODE_ID] ,[PA_DRUGS_ID] ,[PA_EFF_DT] ,[PA_END_DT] ,[CEP_PAY_CD_ID] ,[CEP_ENROLL_CD_ID] ,[CEP_ENROLL_EXCL_DESC] ,[NOVEL_STATUS_IND] ,[FIRST_NOVEL_MNTH] ,[SOURCE] ,[Is_Archived]) SELECT [CODE] ,[GENERIC_NAME] ,[TRADE_NAME] ,[CKPT_INHIB_IND] ,[ANTI_EMETIC_IND] ,[CODE_EFF_DT] ,[NHNR_CANCER_THERAPY] ,[CODE_CATEGORY_ID] ,[ASP_CATEGORY_ID] ,[DRUG_ADM_MODE_ID] ,[PA_DRUGS_ID] ,[PA_EFF_DT] ,[PA_END_DT] ,[CEP_PAY_CD_ID] ,[CEP_ENROLL_CD_ID] ,[CEP_ENROLL_EXCL_DESC] ,[NOVEL_STATUS_IND] ,[FIRST_NOVEL_MNTH] ,[SOURCE] ,0 as [Is_Archived] FROM [chemopx].[ChemotherapyPX_Tracking] WHERE [UPDATE_USER] = @username AND UPDATE_DT = @update_date AND [UPDATE_ACTION] = 'INSERT';

UPDATE Track
SET 
Track.[ChemoPX_Id]  = CASE WHEN Track.[ChemoPX_Id] IS NULL THEN Chemo.[Id] ELSE Track.[ChemoPX_Id] END
FROM [chemopx].[ChemotherapyPX_Tracking] Track
INNER JOIN 
[chemopx].[ChemotherapyPX] Chemo
ON Chemo.[CODE] = Track.[CODE]
WHERE Track.[UPDATE_USER] = @username AND Track.UPDATE_DT =@update_date; --AND Track.[UPDATE_ACTION] = 'INSERT'


--UPDATE
UPDATE Track
SET 
Track.[GENERIC_NAME_PREVIOUS] = CASE WHEN ISNULL(Track.[GENERIC_NAME],'') <> ISNULL(Chemo.[GENERIC_NAME],'') THEN Chemo.[GENERIC_NAME] ELSE Track.[GENERIC_NAME] END,
Track.[TRADE_NAME_PREVIOUS] = CASE WHEN ISNULL(Track.[TRADE_NAME],'') <> ISNULL(Chemo.[TRADE_NAME],'') THEN Chemo.[TRADE_NAME] ELSE Track.[TRADE_NAME] END,
Track.[CKPT_INHIB_IND_PREVIOUS] = CASE WHEN ISNULL(Track.[CKPT_INHIB_IND],'') <> ISNULL(Chemo.[CKPT_INHIB_IND],'') THEN Chemo.[CKPT_INHIB_IND]   ELSE Track.[CKPT_INHIB_IND] END,
Track.[ANTI_EMETIC_IND_PREVIOUS] = CASE WHEN ISNULL(Track.[ANTI_EMETIC_IND],'') <> ISNULL(Chemo.[ANTI_EMETIC_IND],'')THEN Chemo.[ANTI_EMETIC_IND]  ELSE Track.[ANTI_EMETIC_IND] END,
Track.[CODE_EFF_DT_PREVIOUS] = CASE WHEN ISNULL(Track.[CODE_EFF_DT],'') <> ISNULL(Chemo.[CODE_EFF_DT],'') THEN Chemo.[CODE_EFF_DT]  ELSE Track.[CODE_EFF_DT] END,
Track.[NHNR_CANCER_THERAPY_PREVIOUS] = CASE WHEN ISNULL(Track.[NHNR_CANCER_THERAPY],'') <> ISNULL(Chemo.[NHNR_CANCER_THERAPY],'') THEN Chemo.[NHNR_CANCER_THERAPY]  ELSE Track.[NHNR_CANCER_THERAPY] END,
Track.[CODE_CATEGORY_ID_PREVIOUS] = CASE WHEN ISNULL(Track.[CODE_CATEGORY_ID],'') <> ISNULL(Chemo.[CODE_CATEGORY_ID],'') THEN Chemo.[CODE_CATEGORY_ID]  ELSE Track.[CODE_CATEGORY_ID] END,
Track.[ASP_CATEGORY_ID_PREVIOUS] = CASE WHEN ISNULL(Track.[ASP_CATEGORY_ID],'') <> ISNULL(Chemo.[ASP_CATEGORY_ID],'') THEN Chemo.[ASP_CATEGORY_ID] ELSE Track.[ASP_CATEGORY_ID] END,
Track.[DRUG_ADM_MODE_ID_PREVIOUS] = CASE WHEN ISNULL(Track.[DRUG_ADM_MODE_ID],'') <> ISNULL(Chemo.[DRUG_ADM_MODE_ID],'') THEN Chemo.[DRUG_ADM_MODE_ID]  ELSE Track.[DRUG_ADM_MODE_ID] END,
Track.[PA_DRUGS_ID_PREVIOUS] = CASE WHEN ISNULL(Track.[PA_DRUGS_ID],'') <> ISNULL(Chemo.[PA_DRUGS_ID],'') THEN Chemo.[PA_DRUGS_ID] ELSE Track.[PA_DRUGS_ID] END,
Track.[PA_EFF_DT_PREVIOUS] = CASE WHEN ISNULL(Track.[PA_EFF_DT],'') <> ISNULL(Chemo.[PA_EFF_DT],'') THEN Chemo.[PA_EFF_DT]  ELSE Track.[PA_EFF_DT] END,
Track.[PA_END_DT_PREVIOUS] = CASE WHEN ISNULL(Track.[PA_END_DT],'') <> ISNULL(Chemo.[PA_END_DT],'')  THEN Chemo.[PA_END_DT]  ELSE Track.[PA_END_DT] END,
Track.[CEP_PAY_CD_ID_PREVIOUS] = CASE WHEN ISNULL(Track.[CEP_PAY_CD_ID],'') <> ISNULL(Chemo.[CEP_PAY_CD_ID],'')  THEN Chemo.[CEP_PAY_CD_ID]  ELSE Track.[CEP_PAY_CD_ID] END,
Track.[CEP_ENROLL_CD_ID_PREVIOUS] = CASE WHEN ISNULL(Track.[CEP_ENROLL_CD_ID],'') <> ISNULL(Chemo.[CEP_ENROLL_CD_ID],'') THEN Chemo.[CEP_ENROLL_CD_ID]  ELSE Track.[CEP_ENROLL_CD_ID] END,
Track.[CEP_ENROLL_EXCL_DESC_PREVIOUS] = CASE WHEN ISNULL(Track.[CEP_ENROLL_EXCL_DESC],'') <> ISNULL(Chemo.[CEP_ENROLL_EXCL_DESC],'') THEN Chemo.[CEP_ENROLL_EXCL_DESC]  ELSE Track.[CEP_ENROLL_EXCL_DESC] END,
Track.[NOVEL_STATUS_IND_PREVIOUS] = CASE WHEN ISNULL(Track.[NOVEL_STATUS_IND],'') <> ISNULL(Chemo.[NOVEL_STATUS_IND],'')THEN Chemo.[NOVEL_STATUS_IND]  ELSE Track.[NOVEL_STATUS_IND] END,
Track.[FIRST_NOVEL_MNTH_PREVIOUS] = CASE WHEN ISNULL(Track.[FIRST_NOVEL_MNTH],'') <> ISNULL(Chemo.[FIRST_NOVEL_MNTH],'') THEN Chemo.[FIRST_NOVEL_MNTH]  ELSE Track.[FIRST_NOVEL_MNTH] END,
Track.[SOURCE_PREVIOUS] = CASE WHEN ISNULL(Track.[SOURCE],'') <> ISNULL(Chemo.[SOURCE],'')THEN Chemo.[SOURCE]  ELSE Track.[SOURCE] END
FROM [chemopx].[ChemotherapyPX_Tracking] Track
INNER JOIN 
[chemopx].[ChemotherapyPX] Chemo
ON Chemo.[CODE] = Track.[CODE]
WHERE Track.[UPDATE_USER] = @username AND Track.UPDATE_DT =@update_date AND Track.[UPDATE_ACTION] = 'UPDATE'


UPDATE Chemo
SET 

Chemo.[GENERIC_NAME] = CASE WHEN  ISNULL(Track.[GENERIC_NAME],'') <> ISNULL(Chemo.[GENERIC_NAME],'') THEN Track.[GENERIC_NAME] ELSE Chemo.[GENERIC_NAME] END,
Chemo.[TRADE_NAME] = CASE WHEN ISNULL(Track.[TRADE_NAME],'') <> ISNULL(Chemo.[TRADE_NAME],'') THEN Track.[TRADE_NAME] ELSE Chemo.[TRADE_NAME] END,
Chemo.[CKPT_INHIB_IND] = CASE WHEN ISNULL(Track.[CKPT_INHIB_IND],'') <> ISNULL(Chemo.[CKPT_INHIB_IND],'') THEN Track.[CKPT_INHIB_IND] ELSE Chemo.[CKPT_INHIB_IND] END,
Chemo.[ANTI_EMETIC_IND] = CASE WHEN ISNULL(Track.[ANTI_EMETIC_IND],'') <> ISNULL(Chemo.[ANTI_EMETIC_IND],'') THEN Track.[ANTI_EMETIC_IND] ELSE Chemo.[ANTI_EMETIC_IND] END,
Chemo.[CODE_EFF_DT] = CASE WHEN ISNULL(Track.[CODE_EFF_DT],'') <> ISNULL(Chemo.[CODE_EFF_DT],'') THEN Track.[CODE_EFF_DT] ELSE Chemo.[CODE_EFF_DT] END,
Chemo.[NHNR_CANCER_THERAPY] = CASE WHEN ISNULL(Track.[NHNR_CANCER_THERAPY],'') <> ISNULL(Chemo.[NHNR_CANCER_THERAPY],'') THEN Track.[NHNR_CANCER_THERAPY] ELSE Chemo.[NHNR_CANCER_THERAPY] END,
Chemo.[CODE_CATEGORY_ID] = CASE WHEN ISNULL(Track.[CODE_CATEGORY_ID],'') <> ISNULL(Chemo.[CODE_CATEGORY_ID],'') THEN Track.[CODE_CATEGORY_ID] ELSE Chemo.[CODE_CATEGORY_ID] END,
Chemo.[ASP_CATEGORY_ID] = CASE WHEN ISNULL(Track.[ASP_CATEGORY_ID],'') <> ISNULL(Chemo.[ASP_CATEGORY_ID],'') THEN Track.[ASP_CATEGORY_ID] ELSE Chemo.[ASP_CATEGORY_ID] END,
Chemo.[DRUG_ADM_MODE_ID] = CASE WHEN ISNULL(Track.[DRUG_ADM_MODE_ID],'') <> ISNULL(Chemo.[DRUG_ADM_MODE_ID],'') THEN Track.[DRUG_ADM_MODE_ID] ELSE Chemo.[DRUG_ADM_MODE_ID] END,
Chemo.[PA_DRUGS_ID] = CASE WHEN ISNULL(Track.[PA_DRUGS_ID],'') <> ISNULL(Chemo.[PA_DRUGS_ID],'') THEN Track.[PA_DRUGS_ID] ELSE Chemo.[PA_DRUGS_ID] END,
Chemo.[PA_EFF_DT] = CASE WHEN ISNULL(Track.[PA_EFF_DT],'') <> ISNULL(Chemo.[PA_EFF_DT],'') THEN Track.[PA_EFF_DT] ELSE Chemo.[PA_EFF_DT] END,
Chemo.[PA_END_DT] = CASE WHEN ISNULL(Track.[PA_END_DT],'') <> ISNULL(Chemo.[PA_END_DT],'') THEN Track.[PA_END_DT] ELSE Chemo.[PA_END_DT] END,
Chemo.[CEP_PAY_CD_ID] = CASE WHEN ISNULL(Track.[CEP_PAY_CD_ID],'') <> ISNULL(Chemo.[CEP_PAY_CD_ID],'')  THEN Track.[CEP_PAY_CD_ID] ELSE Chemo.[CEP_PAY_CD_ID] END,
Chemo.[CEP_ENROLL_CD_ID] = CASE WHEN ISNULL(Track.[CEP_ENROLL_CD_ID],'') <> ISNULL(Chemo.[CEP_ENROLL_CD_ID],'') THEN Track.[CEP_ENROLL_CD_ID] ELSE Chemo.[CEP_ENROLL_CD_ID] END,
Chemo.[CEP_ENROLL_EXCL_DESC] = CASE WHEN ISNULL(Track.[CEP_ENROLL_EXCL_DESC],'') <> ISNULL(Chemo.[CEP_ENROLL_EXCL_DESC],'') THEN Track.[CEP_ENROLL_EXCL_DESC] ELSE Chemo.[CEP_ENROLL_EXCL_DESC] END,
Chemo.[NOVEL_STATUS_IND] = CASE WHEN ISNULL(Track.[NOVEL_STATUS_IND],'') <> ISNULL(Chemo.[NOVEL_STATUS_IND],'') THEN Track.[NOVEL_STATUS_IND] ELSE Chemo.[NOVEL_STATUS_IND] END,
Chemo.[FIRST_NOVEL_MNTH] = CASE WHEN ISNULL(Track.[FIRST_NOVEL_MNTH],'') <> ISNULL(Chemo.[FIRST_NOVEL_MNTH],'') THEN Track.[FIRST_NOVEL_MNTH] ELSE Chemo.[FIRST_NOVEL_MNTH] END,
Chemo.[SOURCE] = CASE WHEN ISNULL(Track.[SOURCE],'') <> ISNULL(Chemo.[SOURCE],'') THEN Track.[SOURCE] ELSE Chemo.[SOURCE] END
FROM [chemopx].[ChemotherapyPX] Chemo
INNER JOIN 
[chemopx].[ChemotherapyPX_Tracking] Track
ON Chemo.[CODE] = Track.[CODE]
WHERE Track.[UPDATE_USER] = @username AND Track.UPDATE_DT =@update_date AND Track.[UPDATE_ACTION] = 'UPDATE'