CREATE TABLE [peg].[PEG_ANCH_UHPD_SOURCE]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[PEG_ANCH_CATGY] [varchar](11) NULL,
[PEG_ANCH_SBCATGY] [varchar](11) NULL,
[PEG_ANCH_SBCATGY_DESC] [varchar](70) NULL,
[PEG_ANCH_CATGY_ID] [char](5) NULL,
[PEG_ANCH_CATGY_DESC] [varchar](70) NULL,
[PACLocation] [varchar](50) NULL
)
