// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TFS_ClinicalAnalyticsML.Model
{
    public class ModelInput
    {
        [ColumnName("pdf_id"), LoadColumn(0)]
        public string Pdf_id { get; set; }


        [ColumnName("Hydroxychlo"), LoadColumn(1)]
        public bool Hydroxychlo { get; set; }


        [ColumnName("Chloroquine"), LoadColumn(2)]
        public bool Chloroquine { get; set; }


        [ColumnName("Zithromax"), LoadColumn(3)]
        public bool Zithromax { get; set; }


        [ColumnName("VitD"), LoadColumn(4)]
        public bool VitD { get; set; }


        [ColumnName("Magnesium"), LoadColumn(5)]
        public bool Magnesium { get; set; }


        [ColumnName("Prone"), LoadColumn(6)]
        public bool Prone { get; set; }


        [ColumnName("ICU"), LoadColumn(7)]
        public bool ICU { get; set; }


        [ColumnName("Steroid"), LoadColumn(8)]
        public bool Steroid { get; set; }


        [ColumnName("Remdesivir"), LoadColumn(9)]
        public bool Remdesivir { get; set; }


        [ColumnName("EIDD_2801"), LoadColumn(10)]
        public bool EIDD_2801 { get; set; }


        [ColumnName("Antibiotic"), LoadColumn(11)]
        public bool Antibiotic { get; set; }


        [ColumnName("Rocephin"), LoadColumn(12)]
        public bool Rocephin { get; set; }


        [ColumnName("Ceftriaxone"), LoadColumn(13)]
        public bool Ceftriaxone { get; set; }


        [ColumnName("Other_Antibio"), LoadColumn(14)]
        public bool Other_Antibio { get; set; }


        [ColumnName("Zinc"), LoadColumn(15)]
        public bool Zinc { get; set; }


        [ColumnName("Plasma"), LoadColumn(16)]
        public bool Plasma { get; set; }


        [ColumnName("Hyperbar_O2"), LoadColumn(17)]
        public bool Hyperbar_O2 { get; set; }


        [ColumnName("Avigan_Favip"), LoadColumn(18)]
        public bool Avigan_Favip { get; set; }


        [ColumnName("Acterma_Tociliz"), LoadColumn(19)]
        public bool Acterma_Tociliz { get; set; }


        [ColumnName("Kevzara_Sarilumb"), LoadColumn(20)]
        public bool Kevzara_Sarilumb { get; set; }


        [ColumnName("Montelu_Singul"), LoadColumn(21)]
        public bool Montelu_Singul { get; set; }


        [ColumnName("Vit_C"), LoadColumn(22)]
        public bool Vit_C { get; set; }


        [ColumnName("Lovenox_Hep"), LoadColumn(23)]
        public bool Lovenox_Hep { get; set; }


        [ColumnName("Aspirin_ASA"), LoadColumn(24)]
        public bool Aspirin_ASA { get; set; }


        [ColumnName("Vent"), LoadColumn(25)]
        public bool Vent { get; set; }


        [ColumnName("Intubated"), LoadColumn(26)]
        public bool Intubated { get; set; }


        [ColumnName("Vent_Split"), LoadColumn(27)]
        public bool Vent_Split { get; set; }


        [ColumnName("Fever_PosCovid"), LoadColumn(28)]
        public bool Fever_PosCovid { get; set; }


        [ColumnName("PE_Bloodclot"), LoadColumn(29)]
        public bool PE_Bloodclot { get; set; }


        [ColumnName("PulmEmb_DVT_Clot"), LoadColumn(30)]
        public bool PulmEmb_DVT_Clot { get; set; }


        [ColumnName("Pulm_Embolism"), LoadColumn(31)]
        public bool Pulm_Embolism { get; set; }


        [ColumnName("DVT_Bloodclot"), LoadColumn(32)]
        public bool DVT_Bloodclot { get; set; }


        [ColumnName("Atazanavir"), LoadColumn(33)]
        public bool Atazanavir { get; set; }


        [ColumnName("Tenofovir"), LoadColumn(34)]
        public bool Tenofovir { get; set; }


        [ColumnName("Lamivudine"), LoadColumn(35)]
        public bool Lamivudine { get; set; }


        [ColumnName("Ritonavir"), LoadColumn(36)]
        public bool Ritonavir { get; set; }


        [ColumnName("pdf_text"), LoadColumn(37)]
        public string Pdf_text { get; set; }


    }
}
