IF NOT EXISTS (SELECT 1 from  [dbo].[ETG_Dim_Master])
BEGIN 
INSERT INTO [dbo].[ETG_Dim_Master]
           ([ETG_Base_Class]
           ,[ETG_Description]
           ,[ETG_Display])
SELECT  [ETG_Base_Class]
      ,[ETG_Description]
      ,[ETG_Display]
  FROM [VCPostDeploy].[dbo].[ETG_Dim_Master]
END



IF NOT EXISTS (SELECT 1 from  [dbo].[ETG_Dim_Premium_Spec_Master])
BEGIN 
INSERT INTO [dbo].[ETG_Dim_Premium_Spec_Master]
           ([Premium_Specialty_id]
           ,[Premium_Specialty])
SELECT  [Premium_Specialty_id]
      ,[Premium_Specialty]
  FROM [VCPostDeploy].[dbo].[ETG_Dim_Premium_Spec_Master]
END



IF NOT EXISTS (SELECT 1 from  [dbo].[ETG_Fact_Symmetry])
BEGIN 
INSERT INTO [dbo].[ETG_Fact_Symmetry]
           ([ETG_Fact_Symmetry_id]
           ,[ETG_Base_Class]
           ,[Premium_Specialty_id]
           ,[Has_Commercial]
           ,[Has_Medicare]
           ,[Has_Medicaid]
           ,[Has_NRX]
           ,[Has_RX]
           ,[PC_Treatment_Indicator]
           ,[PC_Episode_Count]
           ,[PC_Total_Cost]
           ,[PC_Average_Cost]
           ,[PC_Coefficients_of_Variation]
           ,[PC_Normalized_Pricing_Episode_Count]
           ,[PC_Normalized_Pricing_Total_Cost]
           ,[PC_Spec_Episode_Count]
           ,[PC_Spec_Episode_Distribution]
           ,[PC_Spec_Percent_of_Episodes]
           ,[PC_Spec_Total_Cost]
           ,[PC_Spec_Average_Cost]
           ,[PC_Spec_CV]
           ,[PC_Attribution]
           ,[PC_Change_Comments]
           ,[EC_Treatment_Indicator]
           ,[EC_Episode_Count]
           ,[EC_Total_Cost]
           ,[EC_Average_Cost]
           ,[EC_Coefficients_of_Variation]
           ,[EC_Normalized_Pricing_Episode_Count]
           ,[EC_Normalized_Pricing_Total_Cost]
           ,[EC_Spec_Episode_Count]
           ,[EC_Spec_Episode_Distribution]
           ,[EC_Spec_Percent_of_Episodes]
           ,[EC_Spec_Total_Cost]
           ,[EC_Spec_Average_Cost]
           ,[EC_Spec_CV]
           ,[EC_Mapping]
           ,[EC_Change_Comments]
           ,[Patient_Centric_Mapping]
           ,[Patient_Centric_Change_Comments]
           ,[Symmetry_id]
           ,[Data_Period]
           ,[Data_Date]
           ,[username]
           ,[update_date]
           ,[Symmetry_Version])
   SELECT [ETG_Fact_Symmetry_id]
      ,[ETG_Base_Class]
      ,[Premium_Specialty_id]
      ,[has_Commercial]
      ,[has_Medicare]
      ,[has_Medicaid]
	,[has_nrx]
      ,[has_rx]
      ,[Pop_Cost_Treatment_Indicator]
      ,[Pop_Cost_Episode_Count_Commercial_Only]
      ,[Total_Cost_Commercial_Only]
      ,[Average_Cost_Commercial_Only]
      ,[Coefficients_of_Variation_Commercial_Only]
      ,[Normalized_Pricing_Episode_Count]
      ,[Normalized_Pricing_Total_Cost]
      ,[Specialist_Episode_Count]
      ,[Pop_Cost_Episode_Distribution]
      ,[Percent_of_Episodes]
      ,[Specialist_Total_Cost]
      ,[Specialist_Average_Cost]
      ,[Specialist_CV]
      ,[Attribution]
	  ,[Pop_Cost_Change_Comments]
      ,[Episode_Cost_Treatment_Indicator]
      ,[Episode_Cost_Episode_Count_Commercial_Only]
      ,[Episode_Cost_Total_Cost_Commercial_Only]
      ,[Episode_Cost_Average_Cost_Commercial_Only]
      ,[Episode_Cost_Coefficients_of_Variation_Commercial_Only]
      ,[Episode_Cost_Normalized_Pricing_Episode_Count]
      ,[Episode_Cost_Normalized_Pricing_Total_Cost]
      ,[Episode_Count]
      ,[Episode_Cost_Episode_Distribution]
      ,[Episode_Cost_Percent_of_Episodes]
      ,[Episode_Cost_Total_Cost]
      ,[Episode_Cost_Average_Cost]
      ,[Episode_Cost_Specialist_CV]
      ,[Mapping]
      ,[Episode_Cost_Change_Comments]
      ,[Patient_Centric_Mapping]
      ,[Patient_Centric_Change_Comments]
      ,[Symmetry_id]
      ,[Data_Period]
      ,[Data_Date]
      ,[username]
      ,[update_date]
      ,[Symmetry_Version]
  FROM VCPostDeploy.[dbo].[ETG_Fact_Symmetry]
END


Truncate table [dbo].[ETG_Fact_Symmetry_Update_Tracker];


