CREATE TYPE ChemotherapyPX_Type AS TABLE
(



   [CODE] VARCHAR(7), 
    [CODE_DESC] VARCHAR(100), 
    [GENERIC_NAME] VARCHAR(100), 
    [TRADE_NAME] VARCHAR(50), 
    [CKPT_INHIB_IND] BIT, 
    [ANTI_EMETIC_IND] BIT, 
    [CODE_TYPE] VARCHAR(10), 
    [CODE_EFF_DT] DATE, 
    [CODE_END_DT] DATE, 
    [NHNR_CANCER_THERAPY] BIT, 
    [CODE_CATEGORY] VARCHAR(100), 
    [ASP_CATEGORY] VARCHAR(100), 
    [DRUG_ADM_MODE] VARCHAR(20), 
    [PA_DRUGS] VARCHAR(20), 
    [PA_EFF_DT] DATE, 
    [PA_END_DT] DATE, 
    [CEP_PAY_CD] VARCHAR(50), 
    [CEP_ENROLL_CD] VARCHAR(12), 
    [CEP_ENROLL_EXCL_DESC] VARCHAR(12), 
    [NOVEL_STATUS_IND] BIT, 
    [FIRST_NOVEL_MNTH] INT, 
    [SOURCE] VARCHAR(255), 
    [UPDATE_DT] DATE,
    [Is_Archived] BIT




)