CREATE PROCEDURE [dbo].[sp_ChemotherapyPX_BulkCUD]
	@username varchar(10),
	@update_date DATETIME
AS
 --DELETE
    UPDATE [dbo].[ChemotherapyPX] SET [Is_Archived] = 1 WHERE [Id] in 
  (SELECT [ChemoPX_Id] FROM [dbo].[ChemotherapyPX_Tracking]   WHERE [UPDATE_USER] = @username AND UPDATE_DT = @update_date AND [UPDATE_ACTION] = 'DELETE')

  --INSERT
INSERT INTO [dbo].[ChemotherapyPX] ([CODE] ,[GENERIC_NAME] ,[TRADE_NAME] ,[CKPT_INHIB_IND] ,[ANTI_EMETIC_IND] ,[CODE_EFF_DT] ,[NHNR_CANCER_THERAPY] ,[CODE_CATEGORY_ID] ,[ASP_CATEGORY_ID] ,[DRUG_ADM_MODE_ID] ,[PA_DRUGS_ID] ,[PA_EFF_DT] ,[PA_END_DT] ,[CEP_PAY_CD_ID] ,[CEP_ENROLL_CD_ID] ,[CEP_ENROLL_EXCL_DESC] ,[NOVEL_STATUS_IND] ,[FIRST_NOVEL_MNTH] ,[SOURCE] ,[Is_Archived]) SELECT [CODE] ,[GENERIC_NAME] ,[TRADE_NAME] ,[CKPT_INHIB_IND] ,[ANTI_EMETIC_IND] ,[CODE_EFF_DT] ,[NHNR_CANCER_THERAPY] ,[CODE_CATEGORY_ID] ,[ASP_CATEGORY_ID] ,[DRUG_ADM_MODE_ID] ,[PA_DRUGS_ID] ,[PA_EFF_DT] ,[PA_END_DT] ,[CEP_PAY_CD_ID] ,[CEP_ENROLL_CD_ID] ,[CEP_ENROLL_EXCL_DESC] ,[NOVEL_STATUS_IND] ,[FIRST_NOVEL_MNTH] ,[SOURCE] ,0 as [Is_Archived] FROM [dbo].[ChemotherapyPX_Tracking] WHERE [UPDATE_USER] = @username AND UPDATE_DT = @update_date AND [UPDATE_ACTION] = 'INSERT';

UPDATE Track
SET 
[ChemoPX_Id]  = CASE WHEN Track.[ChemoPX_Id] IS NULL THEN Chemo.[Id] ELSE Track.[ChemoPX_Id] END
FROM [dbo].[ChemotherapyPX_Tracking] Track
INNER JOIN 
[dbo].[ChemotherapyPX] Chemo
ON Chemo.[CODE] = Track.[CODE]
WHERE Track.[UPDATE_USER] = @username AND Track.UPDATE_DT =@update_date; --AND Track.[UPDATE_ACTION] = 'INSERT'


--UPDATE
UPDATE Track
SET 
[GENERIC_NAME_PREVIOUS] = CASE WHEN Track.[GENERIC_NAME] IS NULL THEN NULL ELSE Chemo.[GENERIC_NAME] END,
[TRADE_NAME_PREVIOUS] = CASE WHEN Track.[TRADE_NAME] IS NULL THEN NULL ELSE Chemo.[TRADE_NAME] END,
[CKPT_INHIB_IND_PREVIOUS] = CASE WHEN Track.[CKPT_INHIB_IND] IS NULL THEN NULL  ELSE Chemo.[CKPT_INHIB_IND] END,
[ANTI_EMETIC_IND_PREVIOUS] = CASE WHEN Track.[ANTI_EMETIC_IND] IS NULL THEN NULL  ELSE Chemo.[ANTI_EMETIC_IND] END,
[CODE_EFF_DT_PREVIOUS] = CASE WHEN Track.[CODE_EFF_DT] IS NULL THEN NULL  ELSE Chemo.[CODE_EFF_DT] END,
[NHNR_CANCER_THERAPY_PREVIOUS] = CASE WHEN Track.[NHNR_CANCER_THERAPY] IS NULL THEN NULL  ELSE Chemo.[NHNR_CANCER_THERAPY] END,
[CODE_CATEGORY_ID_PREVIOUS] = CASE WHEN Track.[CODE_CATEGORY_ID] IS NULL THEN NULL  ELSE Chemo.[CODE_CATEGORY_ID] END,
[ASP_CATEGORY_ID_PREVIOUS] = CASE WHEN Track.[ASP_CATEGORY_ID] IS NULL THEN NULL ELSE Chemo.[ASP_CATEGORY_ID] END,
[DRUG_ADM_MODE_ID_PREVIOUS] = CASE WHEN Track.[DRUG_ADM_MODE_ID] IS NULL THEN NULL  ELSE Chemo.[DRUG_ADM_MODE_ID] END,
[PA_DRUGS_ID_PREVIOUS] = CASE WHEN Track.[PA_DRUGS_ID] IS NULL THEN NULL  ELSE Chemo.[PA_DRUGS_ID] END,
[PA_EFF_DT_PREVIOUS] = CASE WHEN Track.[PA_EFF_DT] IS NULL THEN NULL  ELSE Chemo.[PA_EFF_DT] END,
[PA_END_DT_PREVIOUS] = CASE WHEN Track.[PA_END_DT] IS NULL THEN NULL  ELSE Chemo.[PA_END_DT] END,
[CEP_PAY_CD_ID_PREVIOUS] = CASE WHEN Track.[CEP_PAY_CD_ID] IS NULL THEN NULL  ELSE Chemo.[CEP_PAY_CD_ID] END,
[CEP_ENROLL_CD_ID_PREVIOUS] = CASE WHEN Track.[CEP_ENROLL_CD_ID] IS NULL THEN NULL  ELSE Chemo.[CEP_ENROLL_CD_ID] END,
[CEP_ENROLL_EXCL_DESC_PREVIOUS] = CASE WHEN Track.[CEP_ENROLL_EXCL_DESC] IS NULL THEN NULL  ELSE Chemo.[CEP_ENROLL_EXCL_DESC] END,
[NOVEL_STATUS_IND_PREVIOUS] = CASE WHEN Track.[NOVEL_STATUS_IND] IS NULL THEN NULL  ELSE Chemo.[NOVEL_STATUS_IND] END,
[FIRST_NOVEL_MNTH_PREVIOUS] = CASE WHEN Track.[FIRST_NOVEL_MNTH] IS NULL THEN NULL  ELSE Chemo.[FIRST_NOVEL_MNTH] END,
[SOURCE_PREVIOUS] = CASE WHEN Track.[SOURCE] IS NULL THEN NULL  ELSE Chemo.[SOURCE] END
FROM [dbo].[ChemotherapyPX_Tracking] Track
INNER JOIN 
[dbo].[ChemotherapyPX] Chemo
ON Chemo.[CODE] = Track.[CODE]
WHERE Track.[UPDATE_USER] = @username AND Track.UPDATE_DT =@update_date AND Track.[UPDATE_ACTION] = 'UPDATE'


UPDATE Chemo
SET 

[GENERIC_NAME] = CASE WHEN Track.[GENERIC_NAME] IS NULL THEN Chemo.[GENERIC_NAME] ELSE Track.[GENERIC_NAME] END,
[TRADE_NAME] = CASE WHEN Track.[TRADE_NAME] IS NULL THEN Chemo.[TRADE_NAME] ELSE Track.[TRADE_NAME] END,
[CKPT_INHIB_IND] = CASE WHEN Track.[CKPT_INHIB_IND] IS NULL THEN Chemo.[CKPT_INHIB_IND] ELSE Track.[CKPT_INHIB_IND] END,
[ANTI_EMETIC_IND] = CASE WHEN Track.[ANTI_EMETIC_IND] IS NULL THEN Chemo.[ANTI_EMETIC_IND] ELSE Track.[ANTI_EMETIC_IND] END,
[CODE_EFF_DT] = CASE WHEN Track.[CODE_EFF_DT] IS NULL THEN Chemo.[CODE_EFF_DT] ELSE Track.[CODE_EFF_DT] END,
[NHNR_CANCER_THERAPY] = CASE WHEN Track.[NHNR_CANCER_THERAPY] IS NULL THEN Chemo.[NHNR_CANCER_THERAPY] ELSE Track.[NHNR_CANCER_THERAPY] END,
[CODE_CATEGORY_ID] = CASE WHEN Track.[CODE_CATEGORY_ID] IS NULL THEN Chemo.[CODE_CATEGORY_ID] ELSE Track.[CODE_CATEGORY_ID] END,
[ASP_CATEGORY_ID] = CASE WHEN Track.[ASP_CATEGORY_ID] IS NULL THEN Chemo.[ASP_CATEGORY_ID] ELSE Track.[ASP_CATEGORY_ID] END,
[DRUG_ADM_MODE_ID] = CASE WHEN Track.[DRUG_ADM_MODE_ID] IS NULL THEN Chemo.[DRUG_ADM_MODE_ID] ELSE Track.[DRUG_ADM_MODE_ID] END,
[PA_DRUGS_ID] = CASE WHEN Track.[PA_DRUGS_ID] IS NULL THEN Chemo.[PA_DRUGS_ID] ELSE Track.[PA_DRUGS_ID] END,
[PA_EFF_DT] = CASE WHEN Track.[PA_EFF_DT] IS NULL THEN Chemo.[PA_EFF_DT] ELSE Track.[PA_EFF_DT] END,
[PA_END_DT] = CASE WHEN Track.[PA_END_DT] IS NULL THEN Chemo.[PA_END_DT] ELSE Track.[PA_END_DT] END,
[CEP_PAY_CD_ID] = CASE WHEN Track.[CEP_PAY_CD_ID] IS NULL THEN Chemo.[CEP_PAY_CD_ID] ELSE Track.[CEP_PAY_CD_ID] END,
[CEP_ENROLL_CD_ID] = CASE WHEN Track.[CEP_ENROLL_CD_ID] IS NULL THEN Chemo.[CEP_ENROLL_CD_ID] ELSE Track.[CEP_ENROLL_CD_ID] END,
[CEP_ENROLL_EXCL_DESC] = CASE WHEN Track.[CEP_ENROLL_EXCL_DESC] IS NULL THEN Chemo.[CEP_ENROLL_EXCL_DESC] ELSE Track.[CEP_ENROLL_EXCL_DESC] END,
[NOVEL_STATUS_IND] = CASE WHEN Track.[NOVEL_STATUS_IND] IS NULL THEN Chemo.[NOVEL_STATUS_IND] ELSE Track.[NOVEL_STATUS_IND] END,
[FIRST_NOVEL_MNTH] = CASE WHEN Track.[FIRST_NOVEL_MNTH] IS NULL THEN Chemo.[FIRST_NOVEL_MNTH] ELSE Track.[FIRST_NOVEL_MNTH] END,
[SOURCE] = CASE WHEN Track.[SOURCE] IS NULL THEN Chemo.[SOURCE] ELSE Track.[SOURCE] END
FROM [dbo].[ChemotherapyPX] Chemo
INNER JOIN 
[dbo].[ChemotherapyPX_Tracking] Track
ON Chemo.[CODE] = Track.[CODE]
WHERE Track.[UPDATE_USER] = @username AND Track.UPDATE_DT =@update_date AND Track.[UPDATE_ACTION] = 'UPDATE'