CREATE PROCEDURE [dbo].[sp_ChemotherapyPX_Update]
	@Id int,
    @CODE VARCHAR(7), 
    @CODE_DESC VARCHAR(100), 
    @GENERIC_NAME VARCHAR(100), 
    @TRADE_NAME VARCHAR(50), 
    @CKPT_INHIB_IND BIT, 
    @ANTI_EMETIC_IND BIT, 
    @CODE_EFF_DT DATE, 
    @NHNR_CANCER_THERAPY BIT, 
    @CODE_CATEGORY_ID SMALLINT, 
    @ASP_CATEGORY_ID SMALLINT, 
    @DRUG_ADM_MODE_ID SMALLINT, 
    @PA_DRUGS_ID SMALLINT, 
    @PA_EFF_DT DATE, 
    @PA_END_DT DATE, 
    @CEP_PAY_CD_ID SMALLINT, 
    @CEP_ENROLL_CD_ID SMALLINT, 
    @CEP_ENROLL_EXCL_DESC VARCHAR(12), 
    @NOVEL_STATUS_IND BIT , 
    @FIRST_NOVEL_MNTH INT, 
    @SOURCE VARCHAR(255)
AS
BEGIN
UPDATE [dbo].[ChemotherapyPX] SET CODE = @CODE, CODE_DESC =@CODE_DESC, GENERIC_NAME =@GENERIC_NAME, TRADE_NAME = @TRADE_NAME, CKPT_INHIB_IND = @CKPT_INHIB_IND, ANTI_EMETIC_IND =@ANTI_EMETIC_IND, CODE_EFF_DT = @CODE_EFF_DT,  NHNR_CANCER_THERAPY = @NHNR_CANCER_THERAPY, CODE_CATEGORY_ID = @CODE_CATEGORY_ID, ASP_CATEGORY_ID = @ASP_CATEGORY_ID, DRUG_ADM_MODE_ID = @DRUG_ADM_MODE_ID, PA_DRUGS_ID = @PA_DRUGS_ID, PA_EFF_DT = @PA_EFF_DT, PA_END_DT = @PA_END_DT, CEP_PAY_CD_ID= @CEP_PAY_CD_ID, CEP_ENROLL_CD_ID = @CEP_ENROLL_CD_ID, CEP_ENROLL_EXCL_DESC = @CEP_ENROLL_EXCL_DESC, NOVEL_STATUS_IND = @NOVEL_STATUS_IND , FIRST_NOVEL_MNTH= @FIRST_NOVEL_MNTH, SOURCE = @SOURCE WHERE [Id] = @Id;
END

