CREATE TABLE [vct].[NRX_Cost_UGAP]
(
	[ETG_BAS_CLSS_NBR] INT NOT NULL, 
    [TRT_CD] SMALLINT NULL, 
    [MEMBER_COUNT] INT NULL, 
    [EPSD_COUNT] INT NULL, 
    [ETGD_TOT_ALLW_AMT] FLOAT NULL, 
    [ETGD_RX_ALLW_AMT] FLOAT NULL, 
    [RX_RATE] FLOAT NULL 
)
