CREATE TABLE [etgsymm].[ETG_Fact_Symmetry](
       [ETG_Fact_Symmetry_Id] [bigint] NOT NULL,
       [ETG_Base_Class] [varchar](15) NULL,
       [Premium_Specialty_Id] [smallint] NULL,
       [Has_Commercial] [bit] NULL,
       [Has_Medicare] [bit] NULL,
       [Has_Medicaid] [bit] NULL,
	   [Has_NRX] [bit] NULL,
       [Has_RX] [bit] NULL,
       [PC_Treatment_Indicator] [varchar](10) NULL,
       [PC_Episode_Count] [float] NULL,
       [PC_Total_Cost] [float] NULL,
       [PC_Average_Cost] [float] NULL,
       [PC_Coefficients_of_Variation] [float] NULL,
       [PC_Normalized_Pricing_Episode_Count] [float] NULL,
       [PC_Normalized_Pricing_Total_Cost] [float] NULL,
       [PC_Spec_Episode_Count] [float] NULL,
       [PC_Spec_Episode_Distribution] [float] NULL,
       [PC_Spec_Percent_of_Episodes] [float] NULL,
       [PC_Spec_Total_Cost] [float] NULL,
       [PC_Spec_Average_Cost] [float] NULL,
       [PC_Spec_CV] [float] NULL,
	   [PC_Attribution] [varchar](25) NULL,
       [PC_Change_Comments] [ntext] NULL,
       [EC_Treatment_Indicator] [varchar](10) NULL,
       [EC_Episode_Count] [float] NULL,
       [EC_Total_Cost] [float] NULL,
       [EC_Average_Cost] [float] NULL,
       [EC_Coefficients_of_Variation] [float] NULL,
       [EC_Normalized_Pricing_Episode_Count] [float] NULL,
       [EC_Normalized_Pricing_Total_Cost] [float] NULL,
       [EC_Spec_Episode_Count] [float] NULL,
       [EC_Spec_Episode_Distribution] [float] NULL,
       [EC_Spec_Percent_of_Episodes] [float] NULL,
       [EC_Spec_Total_Cost] [float] NULL,
       [EC_Spec_Average_Cost] [float] NULL,
       [EC_Spec_CV] [float] NULL,
	   [EC_Mapping] [varchar](50) NULL,
       [EC_Change_Comments] [ntext] NULL,
	   [Patient_Centric_Mapping] [varchar](25) NULL,
       [Patient_Centric_Change_Comments] [ntext] NULL,
       --[Pop_vs_Episode_Cost_Mapping_Consistency] [varchar](15) NULL,
       --[ETG_Change] [varchar](15) NULL,
       --[Specialist_on_Approved_List] [bit] NULL,
       --[Episode_Cost_Minimum_Volume_Met] [bit] NULL,
       --[Pop_Cost_Minimum_Volume_Met] [bit] NULL,
       [Symmetry_id] [varchar](15) NULL,
       [Data_Period] [varchar](15) NULL,
       [Data_Date] [date] NULL,
       [username] [varchar](10) NULL,
       [update_date] [datetime] NULL,
       [Symmetry_Version] [float] NULL
CONSTRAINT [PK_ETG_Fact_Symmetry] PRIMARY KEY CLUSTERED 
(
       [ETG_Fact_Symmetry_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY], 
    [Is_Mapped] BIT NULL DEFAULT 1
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]