CREATE VIEW [etgsymm].[VW_ETG_Latest_Model]
	AS /****** Script for SelectTopNRows command from SSMS  ******/
SELECT  [Premium_Specialty]
      ,[ETG_Base_Class]
      ,[EC_Treatment_Indicator]
      ,[PC_Episode_Count]
      ,[PC_Total_Cost]
      ,[PC_Average_Cost]
      ,[PC_Coefficients_of_Variation]
      ,[PC_Normalized_Pricing_Episode_Count]
      ,[PC_Normalized_Pricing_Total_Cost]
      ,[PC_Spec_Episode_Count]
      ,[PC_Spec_Total_Cost]
      ,[PC_Spec_Average_Cost]
      ,[PC_Spec_CV]
      ,[PC_Spec_Percent_of_Episodes]
      ,[PC_Spec_Normalized_Pricing_Episode_Count]
      ,[PC_Spec_Normalized_Pricing_Total_Cost]
      ,[PC_Spec_Epsd_Volume]
      ,[EC_Episode_Count]
      ,[EC_Total_Cost]
      ,[EC_Average_Cost]
      ,[EC_Coefficients_of_Variation]
      ,[EC_Normalized_Pricing_Episode_Count]
      ,[EC_Normalized_Pricing_Total_Cost]
      ,[EC_Spec_Episode_Count]
      ,[EC_Spec_Total_Cost]
      ,[EC_Spec_Average_Cost]
      ,[EC_Spec_Coefficients_of_Variation]
      ,[EC_Spec_Percent_of_Episodes]
      ,[EC_Spec_Normalized_Pricing_Episode_Count]
      ,[EC_Spec_Normalized_Pricing_Total_Cost]
      ,[EC_CV3]
      ,[EC_Spec_Episode_Volume]
      ,[PD_Mapped]
      ,[PC_CV3]
      ,[RX_NRX]
      ,[Has_RX]
      ,[Has_NRX]
      ,[RX]
      ,[NRX]
  FROM [etg].[VW_ETG_Final_DataLoad]
