            CREATE INDEX indx_mhp_uni_id ON[mhp].[MHP_Yearly_Universes_UGAP] (mhp_uni_id);
            GO;
            CREATE INDEX indx_LEG_ENTY_NBR ON[mhp].[MHP_Yearly_Universes_UGAP] (LEG_ENTY_NBR);
             GO;
            CREATE INDEX indx_LEG_ENTY_FULL_NM ON[mhp].[MHP_Yearly_Universes_UGAP] (LEG_ENTY_FULL_NM); 
            GO;
            CREATE INDEX indx_MKT_SEG_RLLP_DESC ON[mhp].[MHP_Yearly_Universes_UGAP] (MKT_SEG_RLLP_DESC); 
            GO;
            CREATE INDEX indx_FINC_ARNG_DESC ON[mhp].[MHP_Yearly_Universes_UGAP] (FINC_ARNG_DESC);
            GO;
            CREATE INDEX indx_MKT_TYP_DESC ON[mhp].[MHP_Yearly_Universes_UGAP] (MKT_TYP_DESC);
            GO;
            CREATE INDEX indx_CS_CO_CD_ST ON [mhp].[MHP_Yearly_Universes_UGAP] (CS_CO_CD_ST);
            GO;
            CREATE INDEX indx_PRDCT_SYS_ID ON[mhp].[MHP_Yearly_Universes_UGAP] (PRDCT_SYS_ID); 
            GO;
            CREATE INDEX indx_CS_PRDCT_CD_SYS_ID ON[mhp].[MHP_Yearly_Universes_UGAP] (CS_PRDCT_CD_SYS_ID);
            GO;
            CREATE INDEX indx_CS_CO_CD ON[mhp].[MHP_Yearly_Universes_UGAP] (CS_CO_CD); 
            GO;
            CREATE INDEX indx_State_of_Issue ON[mhp].[MHP_Yearly_Universes] (State_of_Issue); 
            GO;
            CREATE INDEX indx_Authorization ON[mhp].[MHP_Yearly_Universes] ([Authorization]);
             GO;
            CREATE INDEX indx_Request_Decision ON[mhp].[MHP_Yearly_Universes] (Request_Decision);
             GO;
            CREATE INDEX indx_Request_Date ON[mhp].[MHP_Yearly_Universes] (Request_Date);
             GO;
            CREATE INDEX indx_Authorization_Type ON[mhp].[MHP_Yearly_Universes] (Authorization_Type);
             GO;
            CREATE INDEX indx_Decision_Reason ON[mhp].[MHP_Yearly_Universes] (Decision_Reason);
             GO;
            CREATE INDEX indx_file_name ON[mhp].[MHP_Yearly_Universes] (file_name);
             GO;
            CREATE INDEX indx_Group_Number ON [mhp].[MHP_Yearly_Universes] (Group_Number);
             GO;
              CREATE INDEX indx_sheet_name ON[mhp].[MHP_Yearly_Universes] (sheet_name);
               GO;